name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  ci:
    uses: chrisgve/github/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      plugin: tasktamer.nvim
      repo: chrisgve/tasktamer.nvim
