name: Update Repo

on:
  workflow_dispatch:
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  update:
    if: contains(fromJSON('chrisgve'), github.repository_owner)
    uses: chrisgve/github/.github/workflows/update.yml@main
    secrets: inherit
